package model.eo;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 06 15:35:25 CET 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends ApplicationModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for DepartmentsView1.
   * @return DepartmentsView1
   */
  public ViewObjectImpl getDepartmentsView1()
  {
    return (ViewObjectImpl) findViewObject("DepartmentsView1");
  }

  /**
   * Container's getter for DepartmentsView2.
   * @return DepartmentsView2
   */
  public ViewObjectImpl getDepartmentsView2()
  {
    return (ViewObjectImpl) findViewObject("DepartmentsView2");
  }

  /**
   * Container's getter for DepartmentsView3.
   * @return DepartmentsView3
   */
  public ViewObjectImpl getDepartmentsView3()
  {
    return (ViewObjectImpl) findViewObject("DepartmentsView3");
  }

  /**
   * Container's getter for EmployeesView1.
   * @return EmployeesView1
   */
  public ViewObjectImpl getEmployeesView1()
  {
    return (ViewObjectImpl) findViewObject("EmployeesView1");
  }

  /**
   * Container's getter for DeptLinkEmp1.
   * @return DeptLinkEmp1
   */
  public ViewLinkImpl getDeptLinkEmp1()
  {
    return (ViewLinkImpl) findViewLink("DeptLinkEmp1");
  }
}

